name: Build Godot Project

on:
  push: 
    tags:
      - 'v*'

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ProjectIsolation ${{ github.ref }}
          body_path: './ReleaseNotes/${{ github.ref}}.md'
          draft: false
          prerelease: true
      - name: Upload Release - Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/.local/share/godot/archives/windows.zip
          asset_name: 'ProjectIsolation ${{ github.ref}} - windows.zip'
          asset_content_type: application/zip
      - name: Upload Release - Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/.local/share/godot/archives/linux.zip
          asset_name: 'ProjectIsolation ${{ github.ref}} - linux.zip'
          asset_content_type: application/zip
      - name: Upload Release - MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/.local/share/godot/archives/macOS.zip
          asset_name: 'ProjectIsolation ${{ github.ref}} - macOS.zip'
          asset_content_type: application/zip
